apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  postgresql.conf: |
    listen_addresses = '*'
    port = 5432
    max_connections = 100
  pg_hba.conf: |
    local   all             all                                     trust
    host    all             all             0.0.0.0/0              md5
    host    all             all             ::/0                   md5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              key: db_name
              name: bibliotheque-config
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: db_user
              name: bibliotheque-secret
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: db_password
              name: bibliotheque-secret
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-config
          mountPath: /etc/postgresql/postgresql.conf
          subPath: postgresql.conf
        - name: postgres-config
          mountPath: /etc/postgresql/pg_hba.conf
          subPath: pg_hba.conf
      volumes:
      - name: postgres-config
        configMap:
          name: postgres-config